POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "login": "admin",
    "password": "admin"
}

###

POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "login": "admin12",
    "password": "admin12"
}

###

POST http://localhost:3000/api/book
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTYzNDE3Nzc3NCwiZXhwIjoxNjM0MTgxMzc0fQ.HQE3zEzIMQFdD07cCEXeEisBlyxvyzwKSwEIsi8eZos

{
    "title": "Война и мир",
    "date": "2021-10-12",
    "author": 3,
    "description": "qwerty",
    "image": 3
}

###

GET http://localhost:3000/api/books?limit=20
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTYzNDE3Nzc3NCwiZXhwIjoxNjM0MTgxMzc0fQ.HQE3zEzIMQFdD07cCEXeEisBlyxvyzwKSwEIsi8eZos

###

PUT http://localhost:3000/api/book/1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTYzNDE4MTQwNCwiZXhwIjoxNjM0MTg1MDA0fQ.TFCvhVLRFaOw9mVMJ22cG14XEBpiX2ryj9kvTPr0HpU

{
    "title": "Заголовок",
    "date": "2021-10-13",
    "author": 3,
    "description": "qwerty",
    "image": 3
}