POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "login": "admin2asdasdasdsdasd",
    "password": "adminasdasddsdaadasd"
}

###

POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "login": "admin",
    "password": "admin"
}

###

POST http://localhost:3000/api/books/
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM0MTYzNzkxLCJleHAiOjE2MzQxNjczOTF9.d_Du8c5p9g_Sr_8NWT5pijtIh5aBGow48bbqKCjpx6M

{
    "title": "Война и мир",
    "date": "2021-10-13",
    "author": 2920,
    "description": "qwerty",
    "image": 2870
}

###

GET http://localhost:3000/api/books?limit=20
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM0MTYzNzkxLCJleHAiOjE2MzQxNjczOTF9.d_Du8c5p9g_Sr_8NWT5pijtIh5aBGow48bbqKCjpx6M

###

PUT http://localhost:3000/api/books/
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM0MDg3MjUzLCJleHAiOjE2MzQwOTA4NTN9.2XRiUUFfCB4FlwdTVlbq7d9hJzx-JYpfyk1ncu_AjqA

{
    "id": 265454,
    "date": "2021-10-13",
    "author": 2920,
    "description": "qwerty",
    "image": 2870
}